print(f"the integer value for B is {ord('B')}")
print(f"the integer value for C is {ord('C')}")
print(f"the integer value for D is {ord('D')}")
print(f"the integer value for b is {ord('b')}")
print(f"the integer value for c is {ord('c')}")
print(f"the integer value for d is {ord('d')}")
print(f"the integer value for 0 is {ord('0')}")
print(f"the integer value for 1 is {ord('1')}")
print(f"the integer value for 2 is {ord('2')}")
print(f"the integer value for $ is {ord('$')}")
print(f"the integer value for * is {ord('*')}")
print(f"the integer value for + is {ord('+')}")
print(f"the integer value for ' ' is {ord(' ')}")

